import { DocumentType } from './dto/generate-document.dto';

type TemplateMeta = {
  label: string;
  requiredFields: string[];
};

export const DOCUMENT_TEMPLATE_META: Record<DocumentType, TemplateMeta> = {
  rent_agreement: {
    label: 'Rent Agreement',
    requiredFields: [
      'landlordName',
      'tenantName',
      'propertyAddress',
      'monthlyRent',
      'securityDeposit',
      'durationMonths',
      'agreementDate',
    ],
  },
  legal_notice_cheque_bounce: {
    label: 'Legal Notice (Cheque Bounce)',
    requiredFields: [
      'senderName',
      'receiverName',
      'chequeNumber',
      'chequeDate',
      'bankName',
      'amount',
      'noticeDate',
      'paymentDeadlineDays',
    ],
  },
  affidavit_name_change: {
    label: 'Affidavit (Name Change)',
    requiredFields: [
      'deponentName',
      'oldName',
      'newName',
      'fatherOrSpouseName',
      'address',
      'reason',
      'affidavitDate',
    ],
  },
  consumer_complaint: {
    label: 'Consumer Complaint',
    requiredFields: [
      'complainantName',
      'oppositePartyName',
      'productOrService',
      'transactionDate',
      'amountPaid',
      'grievanceSummary',
      'reliefSought',
    ],
  },
  leave_and_license: {
    label: 'Leave and License',
    requiredFields: [
      'licensorName',
      'licenseeName',
      'propertyAddress',
      'licenseFee',
      'securityDeposit',
      'licensePeriodMonths',
      'startDate',
      'lockInPeriodMonths',
    ],
  },
};

export function validateTemplateInput(type: DocumentType, formData: Record<string, unknown>) {
  const requiredFields = DOCUMENT_TEMPLATE_META[type].requiredFields;
  const missing = requiredFields.filter((field) => {
    const value = formData[field];
    return value === undefined || value === null || String(value).trim() === '';
  });

  return {
    valid: missing.length === 0,
    missing,
  };
}

export function renderDocumentText(params: {
  type: DocumentType;
  title: string;
  formData: Record<string, unknown>;
  generatedAtIso: string;
}) {
  const template = DOCUMENT_TEMPLATE_META[params.type];
  const bodyLines = Object.entries(params.formData)
    .map(([key, value]) => `${key}: ${value ?? ''}`)
    .join('\n');

  return [
    `LEGALMITRA - ${template.label.toUpperCase()}`,
    '',
    `Title: ${params.title}`,
    `Generated At: ${params.generatedAtIso}`,
    '',
    '--- DECLARED DETAILS ---',
    bodyLines,
    '',
    '--- DISCLAIMER ---',
    'This draft document is generated by LegalMitra for informational and drafting assistance only.',
    'Please review with a qualified legal professional before use or execution.',
  ].join('\n');
}
